name: test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1 : Build
  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
